import React, { createContext, useContext, useEffect, useState } from 'react'
import { useSettings } from '../hooks/useSupabase'

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    analytics: 'Analytics',
    budget: 'Budget Planner',
    goals: 'Goals',
    borrowLoan: 'Borrow & Lend',
    settings: 'Settings',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    update: 'Update',
    loading: 'Loading...',
    
    // Transactions
    addTransaction: 'Add Transaction',
    editTransaction: 'Edit Transaction',
    income: 'Income',
    expense: 'Expense',
    amount: 'Amount',
    category: 'Category',
    description: 'Description',
    date: 'Date',
    type: 'Type',
    
    // Categories
    food: 'Food',
    transport: 'Transport',
    utilities: 'Utilities',
    entertainment: 'Entertainment',
    healthcare: 'Healthcare',
    shopping: 'Shopping',
    other: 'Other',
    salary: 'Salary',
    freelance: 'Freelance',
    investment: 'Investment',
    business: 'Business',
    rental: 'Rental',
    bonus: 'Bonus',
    gift: 'Gift',
    
    // Dashboard
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    balance: 'Balance',
    recentTransactions: 'Recent Transactions',
    welcome: 'Welcome back',
    financialOverview: 'Here\'s your financial overview for',
    totalBalance: 'Total Balance',
    monthlyIncome: 'Monthly Income',
    monthlyExpenses: 'Monthly Expenses',
    totalTransactions: 'Total Transactions',
    activeGoals: 'Active Goals',
    goalsProgress: 'Goals Progress',
    topCategories: 'Top Categories This Month',
    monthlySavings: 'Monthly Savings',
    thisMonthTransactions: 'This Month\'s Transactions',
    financialHealth: 'Financial Health',
    upcomingBills: 'Upcoming Bills',
    smartInsights: 'Smart Insights',
    todaySummary: 'Today\'s Summary',
    
    // Date filters
    all: 'All',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
    
    // PDF Export
    moneyManager: 'MONEY MANAGER',
    financialTransactionReport: 'Financial Transaction Report',
    generatedOn: 'Generated on',
    financialOverviewPDF: 'FINANCIAL OVERVIEW',
    netBalance: 'NET BALANCE',
    topExpenseCategories: 'TOP EXPENSE CATEGORIES',
    transactionDetails: 'TRANSACTION DETAILS',
    generatedByApp: 'Generated by Money Manager App - Your Personal Finance Companion',
    reportContains: 'Report contains',
    page: 'Page',
    pdfGeneratedSuccess: 'Creative PDF report generated successfully! 🎉'
  },
  hi: {
    // Navigation
    dashboard: 'डैशबोर्ड',
    transactions: 'लेन-देन',
    analytics: 'विश्लेषण',
    budget: 'बजट योजना',
    goals: 'लक्ष्य',
    borrowLoan: 'उधार और कर्ज',
    settings: 'सेटिंग्स',
    
    // Common
    save: 'सेव करें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    update: 'अपडेट करें',
    loading: 'लोड हो रहा है...',
    
    // Transactions
    addTransaction: 'लेन-देन जोड़ें',
    editTransaction: 'लेन-देन संपादित करें',
    income: 'आय',
    expense: 'व्यय',
    amount: 'राशि',
    category: 'श्रेणी',
    description: 'विवरण',
    date: 'तारीख',
    type: 'प्रकार',
    
    // Categories
    food: 'भोजन',
    transport: 'परिवहन',
    utilities: 'उपयोगिताएं',
    entertainment: 'मनोरंजन',
    healthcare: 'स्वास्थ्य सेवा',
    shopping: 'खरीदारी',
    other: 'अन्य',
    salary: 'वेतन',
    freelance: 'फ्रीलांस',
    investment: 'निवेश',
    business: 'व्यापार',
    rental: 'किराया',
    bonus: 'बोनस',
    gift: 'उपहार',
    
    // Dashboard
    totalIncome: 'कुल आय',
    totalExpenses: 'कुल व्यय',
    balance: 'शेष राशि',
    recentTransactions: 'हाल के लेन-देन',
    welcome: 'वापस आपका स्वागत है',
    financialOverview: 'यहाँ आपका वित्तीय अवलोकन है',
    totalBalance: 'कुल शेष राशि',
    monthlyIncome: 'मासिक आय',
    monthlyExpenses: 'मासिक व्यय',
    totalTransactions: 'कुल लेन-देन',
    activeGoals: 'सक्रिय लक्ष्य',
    goalsProgress: 'लक्ष्य प्रगति',
    topCategories: 'इस महीने की शीर्ष श्रेणियाँ',
    monthlySavings: 'मासिक बचत',
    thisMonthTransactions: 'इस महीने के लेन-देन',
    financialHealth: 'वित्तीय स्वास्थ्य',
    upcomingBills: 'आगामी बिल',
    smartInsights: 'स्मार्ट अंतर्दृष्टि',
    todaySummary: 'आज का सारांश',
    
    // Date filters
    all: 'सभी',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    yearly: 'वार्षिक',
    today: 'आज',
    yesterday: 'कल',
    tomorrow: 'कल',
    
    // PDF Export
    moneyManager: 'मनी मैनेजर',
    financialTransactionReport: 'वित्तीय लेन-देन रिपोर्ट',
    generatedOn: 'पर जेनरेट किया गया',
    financialOverviewPDF: 'वित्तीय अवलोकन',
    netBalance: 'नेट बैलेंस',
    topExpenseCategories: 'शीर्ष व्यय श्रेणियां',
    transactionDetails: 'लेन-देन विवरण',
    generatedByApp: 'मनी मैनेजर ऐप द्वारा जेनरेट किया गया - आपका व्यक्तिगत वित्त साथी',
    reportContains: 'रिपोर्ट में शामिल है',
    page: 'पेज',
    pdfGeneratedSuccess: 'रचनात्मक पीडीएफ रिपोर्ट सफलतापूर्वक जेनरेट की गई! 🎉'
  },
  gu: {
    // Navigation
    dashboard: 'ડેશબોર્ડ',
    transactions: 'લેણ-દેણ',
    analytics: 'વિશ્લેષણ',
    budget: 'બજેટ યોજના',
    goals: 'લક્ષ્યો',
    borrowLoan: 'ઉધાર અને કર્જ',
    settings: 'સેટિંગ્સ',
    
    // Common
    save: 'સેવ કરો',
    cancel: 'રદ્દ કરો',
    delete: 'ડિલીટ કરો',
    edit: 'સંપાદિત કરો',
    add: 'જોડો',
    update: 'અપડેટ કરો',
    loading: 'લોડ થઈ રહ્યું છે...',
    
    // Transactions
    addTransaction: 'લેણ-દેણ જોડો',
    editTransaction: 'લેણ-દેણ સંપાદિત કરો',
    income: 'આવક',
    expense: 'ખર્ચ',
    amount: 'રકમ',
    category: 'વર્ગ',
    description: 'વર્ણન',
    date: 'તારીખ',
    type: 'પ્રકાર',
    
    // Categories
    food: 'ખાણું',
    transport: 'પરિવહન',
    utilities: 'ઉપયોગિતાઓ',
    entertainment: 'મનોરંજન',
    healthcare: 'આરોગ્ય સેવા',
    shopping: 'ખરીદારી',
    other: 'અન્ય',
    salary: 'પગાર',
    freelance: 'ફ્રીલાન્સ',
    investment: 'ગુંતવણૂક',
    business: 'વ્યવસાય',
    rental: 'ભાડું',
    bonus: 'બોનસ',
    gift: 'ઉપહાર',
    
    // Dashboard
    totalIncome: 'કુલ આવક',
    totalExpenses: 'કુલ ખર્ચ',
    balance: 'બાકી રકમ',
    recentTransactions: 'હાલના લેણ-દેણ',
    welcome: 'વાપસ આવકાર',
    financialOverview: 'અહીં તમારું ફાઇનાન્સિયલ ઓવરવ્યુ છે',
    totalBalance: 'કુલ બાકી રકમ',
    monthlyIncome: 'માસિક આવક',
    monthlyExpenses: 'માસિક ખર્ચ',
    totalTransactions: 'કુલ લેણ-દેણ',
    activeGoals: 'સક્રિય લક્ષ્યો',
    goalsProgress: 'લક્ષ્યોની પ્રગતિ',
    topCategories: 'આ મહિનાની શીર્ષ વર્ગો',
    monthlySavings: 'માસિક બચત',
    thisMonthTransactions: 'આ મહિનાના લેણ-દેણ',
    financialHealth: 'ફાઇનાન્સિયલ હેલ્થ',
    upcomingBills: 'આવતા બિલ',
    smartInsights: 'સ્માર્ટ ઇન્સાઇટ્સ',
    todaySummary: 'આજેનો સારાંશ',
    
    // Date filters
    all: 'બધું',
    daily: 'દૈનિક',
    weekly: 'સાપ્તાહિક',
    monthly: 'માસિક',
    yearly: 'વાર્ષિક',
    today: 'આજે',
    yesterday: 'ગઇકાલે',
    tomorrow: 'આવતી કાલે',
    
    // PDF Export
    moneyManager: 'મની મેનેજર',
    financialTransactionReport: 'ફાઇનાન્સિયલ ટ્રાન્ઝેક્શન રિપોર્ટ',
    generatedOn: 'પર જનરેટ કર્યું',
    financialOverviewPDF: 'ફાઇનાન્સિયલ ઓવરવ્યુ',
    netBalance: 'નેટ બેલેન્સ',
    topExpenseCategories: 'ટોચની ખર્ચ વર્ગો',
    transactionDetails: 'લેણ-દેણ વિગતો',
    generatedByApp: 'મની મેનેજર એપ દ્વારા જનરેટ કર્યું - તમારો વ્યક્તિગત ફાઇનાન્સ સાથી',
    reportContains: 'રિપોર્ટમાં સમાવેશ થાય છે',
    page: 'પેજ',
    pdfGeneratedSuccess: 'સર્જનાત્મક પીડીએફ રિપોર્ટ સફળતાપૂર્વક જનરેટ થઈ! 🎉'
  },
  mr: {
    // Navigation
    dashboard: 'डॅशबोर्ड',
    transactions: 'व्यवहार',
    analytics: 'विश्लेषण',
    budget: 'अंदाजपत्रक योजना',
    goals: 'उद्दिष्टे',
    borrowLoan: 'उधार आणि कर्ज',
    settings: 'सेटिंग्ज',
    
    // Common
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    edit: 'संपादित करा',
    add: 'जोडा',
    update: 'अपडेट करा',
    loading: 'लोड होत आहे...',
    
    // Transactions
    addTransaction: 'व्यवहार जोडा',
    editTransaction: 'व्यवहार संपादित करा',
    income: 'उत्पन्न',
    expense: 'खर्च',
    amount: 'रक्कम',
    category: 'वर्ग',
    description: 'वर्णन',
    date: 'तारीख',
    type: 'प्रकार',
    
    // Categories
    food: 'अन्न',
    transport: 'वाहतूक',
    utilities: 'सुविधा',
    entertainment: 'मनोरंजन',
    healthcare: 'आरोग्य सेवा',
    shopping: 'खरेदी',
    other: 'इतर',
    salary: 'पगार',
    freelance: 'मुक्त व्यवसाय',
    investment: 'गुंतवणूक',
    business: 'व्यवसाय',
    rental: 'भाडे',
    bonus: 'बोनस',
    gift: 'भेट',
    
    // Dashboard
    totalIncome: 'एकूण उत्पन्न',
    totalExpenses: 'एकूण खर्च',
    balance: 'शिल्लक',
    recentTransactions: 'अलीकडील व्यवहार',
    welcome: 'परत आला आहात',
    financialOverview: 'येथे तुमचा आर्थिक आढावा आहे',
    totalBalance: 'एकूण शिल्लक',
    monthlyIncome: 'मासिक उत्पन्न',
    monthlyExpenses: 'मासिक खर्च',
    totalTransactions: 'एकूण व्यवहार',
    activeGoals: 'सक्रिय उद्दिष्टे',
    goalsProgress: 'उद्दिष्टांची प्रगती',
    topCategories: 'या महिन्यातील शीर्ष वर्ग',
    monthlySavings: 'मासिक बचत',
    thisMonthTransactions: 'या महिन्याचे व्यवहार',
    financialHealth: 'आर्थिक आरोग्य',
    upcomingBills: 'येणारी बिले',
    smartInsights: 'स्मार्ट अंतर्दृष्टी',
    todaySummary: 'आजचा सारांश',
    
    // Date filters
    all: 'सर्व',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    yearly: 'वार्षिक',
    today: 'आज',
    yesterday: 'काल',
    tomorrow: 'उद्या',
    
    // PDF Export
    moneyManager: 'मनी मॅनेजर',
    financialTransactionReport: 'आर्थिक व्यवहार अहवाल',
    generatedOn: 'वर तयार केले',
    financialOverviewPDF: 'आर्थिक आढावा',
    netBalance: 'निव्वळ शिल्लक',
    topExpenseCategories: 'शीर्ष खर्च वर्ग',
    transactionDetails: 'व्यवहार तपशील',
    generatedByApp: 'मनी मॅनेजर अॅपद्वारे तयार केले - तुमचा वैयक्तिक वित्त साथी',
    reportContains: 'अहवालात समाविष्ट आहे',
    page: 'पान',
    pdfGeneratedSuccess: 'सर्जनशील पीडीएफ अहवाल यशस्वीरित्या तयार झाला! 🎉'
  }
}

interface PreferencesContextType {
  currency: string
  language: string
  dateFormat: string
  formatCurrency: (amount: number) => string
  formatDate: (date: string | Date) => string
  t: (key: string) => string
  updatePreferences: (newPrefs: Partial<{ currency: string; language: string; dateFormat: string }>) => void
}

const PreferencesContext = createContext<PreferencesContextType | undefined>(undefined)

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const { settings, updateSettings } = useSettings()
  const [preferences, setPreferences] = useState({
    currency: 'INR',
    language: 'en',
    dateFormat: 'dd-mm-yyyy'
  })

  useEffect(() => {
    if (settings) {
      setPreferences({
        currency: settings.currency,
        language: settings.language,
        dateFormat: settings.date_format
      })
    }
  }, [settings])

  const updatePreferences = async (newPrefs: Partial<{ currency: string; language: string; dateFormat: string }>) => {
    const updatedPrefs = { ...preferences, ...newPrefs }
    setPreferences(updatedPrefs)
    
    // Update settings in database
    if (updateSettings) {
      await updateSettings({
        currency: updatedPrefs.currency,
        language: updatedPrefs.language,
        date_format: updatedPrefs.dateFormat
      })
    }
  }

  const formatCurrency = (amount: number): string => {
    const currencyConfig = {
      INR: { symbol: '₹', locale: 'en-IN' },
      USD: { symbol: '$', locale: 'en-US' },
      EUR: { symbol: '€', locale: 'de-DE' },
      GBP: { symbol: '£', locale: 'en-GB' }
    }
    
    const config = currencyConfig[preferences.currency as keyof typeof currencyConfig] || currencyConfig.INR
    return `${config.symbol}${amount.toLocaleString(config.locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  }

  const formatDate = (date: string | Date): string => {
    const dateObj = typeof date === 'string' ? new Date(date) : date
    
    const localeMap = {
      en: 'en-US',
      hi: 'hi-IN',
      gu: 'gu-IN',
      mr: 'mr-IN'
    }
    
    const locale = localeMap[preferences.language as keyof typeof localeMap] || 'en-US'
    
    switch (preferences.dateFormat) {
      case 'mm-dd-yyyy':
        return dateObj.toLocaleDateString('en-US')
      case 'yyyy-mm-dd':
        return dateObj.toISOString().split('T')[0]
      case 'dd-mm-yyyy':
      default:
        return dateObj.toLocaleDateString(locale)
    }
  }

  const t = (key: string): string => {
    const langTranslations = translations[preferences.language as keyof typeof translations] || translations.en
    return langTranslations[key as keyof typeof langTranslations] || key
  }

  return (
    <PreferencesContext.Provider value={{
      ...preferences,
      formatCurrency,
      formatDate,
      t,
      updatePreferences
    }}>
      {children}
    </PreferencesContext.Provider>
  )
}

export function usePreferences() {
  const context = useContext(PreferencesContext)
  if (context === undefined) {
    throw new Error('usePreferences must be used within a PreferencesProvider')
  }
  return context
}